# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17JMhxXX1-4wLNcKXY5wuxovA_l_ycugV
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Style Pro
plt.style.use('seaborn-v0_8-paper')

# --- GRAPHIQUE 1 : L'EFFET LEAD-LAG (Théorique) ---
t = np.linspace(0, 20, 100)
# Le Prime (LMT) réagit instantanément au choc en t=5
prime_price = np.where(t < 5, 100, 105 + np.random.normal(0, 0.2, 100))
# Le Supplier (MOG.A) met du temps à monter (réponse exponentielle)
supplier_price = np.where(t < 5, 100, 100 + 5 * (1 - np.exp(-0.5 * (t - 5))) + np.random.normal(0, 0.2, 100))

plt.figure(figsize=(10, 5))
plt.plot(t, prime_price, label='Prime Contractor (LMT) - Instant Reaction', linewidth=2, color='#003366')
plt.plot(t, supplier_price, label='Supplier (MOG.A) - Lagged Reaction', linewidth=2, color='#D35400', linestyle='--')
plt.axvline(x=5, color='gray', linestyle=':', label='News Arrival (Contract Award)')
plt.title('Microstructure Friction: Visualizing the Information Diffusion Lag', fontsize=12, fontweight='bold')
plt.xlabel('Time (Trading Hours)')
plt.ylabel('Normalized Price')
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig('lead_lag_visual.png', dpi=300)
plt.close()

# --- GRAPHIQUE 2 : EQUITY CURVE (Basé sur tes stats) ---
np.random.seed(42)
n_trades = 79
returns = np.random.choice([0.0084, -0.0062], size=n_trades, p=[0.56, 0.44]) # Win rate 56%
cum_returns = np.cumprod(1 + returns) * 100

plt.figure(figsize=(10, 5))
plt.plot(cum_returns, label='L/S Supply Chain Strategy (Net of Costs)', color='#27AE60', linewidth=1.5)
plt.plot(np.linspace(100, 100, n_trades), label='Market Neutral Baseline', color='black', linestyle='--', alpha=0.5)
plt.title('Cumulative Performance: Strategy vs Market Neutral Benchmark (2022-2026)', fontsize=12, fontweight='bold')
plt.xlabel('Trade Count')
plt.ylabel('Portfolio Value (Base 100)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig('equity_curve.png', dpi=300)
plt.close()

print("Graphiques générés : lead_lag_visual.png et equity_curve.png")